### ISSUE TITLE
How to change the font size of body text？

### ISSUE THREAD

**Issue by LyraGit** [etigerstudio/typora-misty-theme#17]
@etigerstudio 
Hello，
The font size of the title is fine. I want to adjust the font size of the body text and want to make it bigger. What do I have to change in the code please?

![1](https://github.com/user-attachments/assets/c338b115-c254-4385-b389-e095bff0c097)

Thanks.

**Comment by etigerstudio** [comment]
Sry for my late response! 

It's quite easy to change the font size of the body text. You may just open the CSS file and adjust the font size to whatever you like in Line 12 (below the `html` selector). Restart Typora and it's done！🎉

<img width="494" alt="Screenshot 2024-09-23 at 17 04 56" src="https://github.com/user-attachments/assets/ddb19162-1552-4bae-95a6-26f7e745d679">

Thank you for trying out this theme! Hope you are happy with it!
