### ISSUE TITLE
Task Lists render misaligned

### ISSUE THREAD

**Issue by swissmanu** [etigerstudio/typora-misty-theme#2]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/170832/51254671-d70ea100-19a1-11e9-9404-d9115a9124c9.png">

will give it a try to fix if i find some time. will do a PR in that case :)

clean looking theme btw. thank you!

**Comment by etigerstudio** [comment]
Thank you for trying this theme out and spotting this problem. I'm very glad to hear that you liked it!
As for the bug, I also will try to address it in the next few days.

**Comment by etigerstudio** [comment]
Hi! This issued has been addressed and the fix has been applied in [latest release](https://github.com/etigerstudio/typora-misty-theme/releases/tag/v0.2.1).

----
Current rendering layout:
<img width="216" alt="screen shot 2019-01-16 at 11 36 31 pm" src="https://user-images.githubusercontent.com/2973222/51261396-1d3c2280-19eb-11e9-85bf-97bb8273cef6.png">
Even looks good when customized font size enabled:
<img width="352" alt="screen shot 2019-01-16 at 11 36 50 pm" src="https://user-images.githubusercontent.com/2973222/51261551-6d1ae980-19eb-11e9-8998-f6e1aff90a57.png">
And, of course, on Windows:
<img width="232" alt="screen shot 2019-01-16 at 11 56 19 pm" src="https://user-images.githubusercontent.com/2973222/51261612-86bc3100-19eb-11e9-86a7-fda12caa3abc.png">

If you find any other problem or have any other idea on the theme, free feel to open up another issue!
