### ISSUE TITLE
dark mode? (MacOS)

### ISSUE THREAD

**Issue by daiooo** [etigerstudio/typora-misty-theme#3]
Plan to support dark mode in MacOS?

tks

**Comment by etigerstudio** [comment]
That's a great idea which didn't occur to me before. I'll try to create a theme with both new dark color scheme and original Misty experience in the next few days.
So please stay tuned for the upcoming dark mode!

**Comment by etigerstudio** [comment]
A preview dark mode theme for macOS has been [released](https://github.com/etigerstudio/typora-misty-theme/releases/tag/v0.3-alpha)🎉. You may try it out now. More features & bug fixes will come in next releases.

**Comment by etigerstudio** [comment]
Stable Misty Dark has been released, thus I'm closing the issue for now. If you have any further question, feel free to open another issue.
