### ISSUE TITLE
字体仍显示为默认字体

### ISSUE THREAD

**Issue by Mike-7777777** [etigerstudio/typora-misty-theme#6]
Windows 10 专业版 1803 
将css文件粘贴到主题目录中重启typora并选中该主题后文本的字体不论中英文都未发生改变。

**Comment by etigerstudio** [comment]
你好，首先非常感谢你试用这款主题😃。
你遇到的问题是字体没有改变对吗？如果是这样，这是正常的。因为无论在Windows还是macOS平台上，Misty主题都使用的是系统默认字体（对于Windows可能就是微软雅黑和Segoe UI）。这款主题主要是自定义了字号、字重、背景色、前景色等这方面的样式。
如果你还有其他问题或者想法欢迎继续交流🤓。
